version: '3.1'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
      - init_db
    links:
      - db:db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  init_db:
    build: .
    command: ['/bin/bash', '-c', 'npx knex migrate:latest && npx knex seed:run']
    links:
      - db:db
    depends_on:
      - db
